import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/Home/Hero";
import Search from "@/components/Home/Search";
import GameList from "@/components/Home/GameList";
import { getFirestore, doc, setDoc, getDoc, 
  collection, getDocs, query, where } from "firebase/firestore";
  import app from '../shared/FirebaseConfig'
import { useEffect, useState } from "react";
import Posts from "@/components/Home/Posts";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const db = getFirestore(app);
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    getPost();
  }, []);

  const getPost = async () => {
    const querySnapshot = await getDocs(collection(db, "posts"));
    const postsArray = [];
    querySnapshot.forEach((doc) => {
     
      postsArray.push(doc.data());
    });
    setPosts(postsArray);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <div className="px-5 sm:px-7 md:px-10 mt-9"  >
      <Hero/>
      <Search/>
      <GameList/>
     { posts?<Posts posts={posts}/>:null} 
      </div>
      </>
    </>
  );
}
